name = "PokeMoon"
author = "HazelMoon"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6682b939499bd3dc84f2bcbf617d7f4248a17585f3fff8fcb799fad90376b72"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
